gui:
  title: "&8Kaucjomat"
  size: 27
  input-slots: [11, 12, 13, 14, 15]
  button-slot: 22
  button:
    material: EMERALD_BLOCK
    name: "&a&lWYMIEŃ BUTELKI"
    lore:
      - "&7Kliknij, aby sprzedać butelki."
      - "&7Otrzymasz: &e{MONEY}$ &7za każde &b{BOTTLES} sztuk&7!"
  background:
    material: GRAY_STAINED_GLASS_PANE
    name: " "

bottle:
  material: GLASS_BOTTLE
  name: "&aButelka Kaucyjna"
  lore:
    - "&7Wymień ją w kaucjomacie"
    - "&7Tylko do użytku ekologicznego!"

economy:
  bottles-required: 5
  money-reward: 10.0

messages:
  prefix: "&8[&aKaucjomat&8] &7"
  no-permission: "&cNie masz uprawnień!"
  reloaded: "&aPrzeładowano konfigurację!"
  given: "&aOtrzymałeś butelkę kaucyjną!"
  not-enough-bottles: "&cWłożyłeś za mało butelek! Minimum to {MIN}."
  success: "&aPomyślnie wymieniono &e{AMOUNT} &abutelek na &e{MONEY}$&a!"
  inventory-full: "&cMasz pełny ekwipunek, zwrócone butelki wypadły na ziemię!"